FROM ghcr.io/cyberworm-uk/base:latest
RUN apk --no-cache --no-interactive add tor
COPY torrc /etc/tor/torrc-defaults
VOLUME [ "/var/lib/tor" ]
HEALTHCHECK CMD tor-resolve 127.0.0.1
ENTRYPOINT [ "/usr/bin/tor" ]
