FROM docker.io/library/alpine:latest
LABEL org.opencontainers.image.base.name="docker.io/library/alpine"
LABEL org.opencontainers.image.title="Tor base"
LABEL org.opencontainers.image.description="Tor base alpine image"
RUN apk --no-cache --no-interactive add tor
COPY torrc /etc/tor/torrc-defaults
VOLUME [ "/var/lib/tor" ]
HEALTHCHECK CMD tor-resolve 127.0.0.1
ENTRYPOINT [ "/usr/bin/tor" ]