# https://gitlab.torproject.org/tpo/core/arti/-/blob/main/crates/arti/src/arti-example-config.toml
[proxy]
socks_listen = "0.0.0.0:9050"
[logging]
console = "info"
[storage]
cache_dir = "/arti/cache"
state_dir = "/arti/state"
[address_filter]
allow_onion_addrs = true