FROM ghcr.io/guest42069/snowflake:latest AS bin

FROM ghcr.io/guest42069/torbase:latest
COPY --from=bin /client /usr/bin/client
EXPOSE 9050
ENTRYPOINT [ "/usr/bin/tor", "--clienttransportplugin", "snowflake exec /usr/bin/client -url https://snowflake-broker.torproject.net.global.prod.fastly.net/ -front cdn.sstatic.net -ice stun:stun.l.google.com:19302,stun:stun.voip.blackberry.com:3478,stun:stun.altar.com.pl:3478,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.sonetel.net:3478,stun:stun.stunprotocol.org:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478", "--socksport", "0.0.0.0:9050", "--usebridges", "1", "--bridge", "snowflake 192.0.2.3:1 2B280B23E1107BB62ABFC40DDCC8824814F80A72" ]