FROM ghcr.io/cyberworm-uk/snowflake:latest AS bin

FROM ghcr.io/cyberworm-uk/tor-base:latest
LABEL org.opencontainers.image.base.name="ghcr.io/cyberworm-uk/tor-base"
LABEL org.opencontainers.image.title="Snowflake Proxy"
LABEL org.opencontainers.image.description="Snowflake Proxy"
COPY --from=bin /client /usr/bin/client
EXPOSE 9050
ENTRYPOINT [ "/usr/bin/tor", \
  "--clienttransportplugin",  "snowflake exec /usr/bin/client", \
  "--socksport", "0.0.0.0:9050", \
  "--usebridges", "1", \
  "--bridge", "snowflake 192.0.2.3:80 2B280B23E1107BB62ABFC40DDCC8824814F80A72 fingerprint=2B280B23E1107BB62ABFC40DDCC8824814F80A72 url=https://1098762253.rsc.cdn77.org/ fronts=www.cdn77.com,www.phpmyadmin.net ice=stun:stun.l.google.com:19302,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478 utls-imitate=hellorandomizedalpn", \
  "--bridge", "snowflake 192.0.2.4:80 8838024498816A039FCBBAB14E6F40A0843051FA fingerprint=8838024498816A039FCBBAB14E6F40A0843051FA url=https://1098762253.rsc.cdn77.org/ fronts=www.cdn77.com,www.phpmyadmin.net ice=stun:stun.l.google.com:19302,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.net:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478 utls-imitate=hellorandomizedalpn" \
]