FROM --platform=$BUILDPLATFORM docker.io/alpine/git:latest AS source
WORKDIR /go/src
ARG VERSION=main
RUN git clone --depth=1 --branch=${VERSION} https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird.git .

FROM --platform=$BUILDPLATFORM docker.io/library/golang:alpine AS build
ARG TARGETOS TARGETARCH
ENV GOOS="$TARGETOS" GOARCH="$TARGETARCH" GOFLAGS="-buildvcs=false -trimpath" CGO_ENABLED=0
COPY --from=source /go/src /go/src
WORKDIR /go/src
RUN --mount=type=cache,target=/go/pkg go mod download
RUN --mount=type=cache,target=/go/pkg --mount=type=cache,target=/root/.cache/go-build go build -ldflags '-w -s -buildid=' -o /lyrebird ./cmd/lyrebird

FROM scratch
COPY --from=build /lyrebird /lyrebird
