FROM ghcr.io/guest42069/obfs4:latest AS bin

FROM ghcr.io/guest42069/torbase:latest
COPY --from=bin /obfs4proxy /usr/bin/obfs4proxy
RUN setcap cap_net_bind_service=ep /usr/bin/obfs4proxy
EXPOSE 443 27045
ENTRYPOINT [ "/usr/bin/tor", "--servertransportplugin", "obfs4 exec /usr/bin/obfs4proxy", "--orport", "27045", "--extorport", "auto", "--servertransportlistenaddr", "obfs4 0.0.0.0:443" ]
