FROM ghcr.io/guest42069/lyrebird:latest AS bin

FROM ghcr.io/guest42069/torbase:latest
COPY --from=bin /lyrebird /usr/bin/lyrebird
RUN --mount=type=cache,target=/apk apk --cache-dir /apk --no-interactive add libcap-utils
RUN setcap cap_net_bind_service=+ep /usr/bin/lyrebird
EXPOSE 443
ENTRYPOINT [ "/usr/bin/tor", "--bridgerelay", "1", "--servertransportplugin", "obfs4 exec /usr/bin/lyrebird", "--extorport", "auto", "--servertransportlistenaddr", "obfs4 0.0.0.0:443" ]