FROM ghcr.io/guest42069/obfs4:latest AS bin

FROM ghcr.io/guest42069/torbase:latest
COPY --from=bin /obfs4proxy /usr/bin/obfs4proxy
ENTRYPOINT [ "/usr/bin/tor", "--clienttransportplugin", "obfs4 exec /usr/bin/obfs4proxy", "--socksport", "0.0.0.0:9050", "--usebridges", "1", "--user", "tor" ]
