FROM docker.io/alpine/git:latest AS source
ARG VERSION=main
WORKDIR /go/src
RUN git clone --depth=1 --branch=${VERSION} https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake.git .

FROM docker.io/library/golang:1.17-alpine AS build
COPY --from=source /go/src /go/src
WORKDIR /go/src/client
RUN go mod download
RUN if [[ "`go env | grep "^GOARCH=" | sed 's:GOARCH="\(.*\)":\1:'`" != "arm" ]]; then export PIE="-buildmode=pie"; fi
RUN CGO_ENABLED=0 go build -ldflags '-extldflags "-static" -w -s -buildid=' -trimpath $PIE .

FROM scratch
COPY --from=build /go/src/client/client /client
