FROM docker.io/alpine/git:latest AS source
ARG VERSION=main
WORKDIR /go/src
RUN git clone --depth=1 --branch=${VERSION} https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake.git .

FROM docker.io/library/golang:1.17-alpine AS build
COPY --from=source /go/src /go/src
WORKDIR /go/src/client
RUN go mod download
RUN CGO_ENABLED=0 go build -o client -ldflags '-extldflags "-static" -w -s'  .

FROM scratch
COPY --from=build /go/src/client/client /client
