FROM docker.io/alpine/git:latest AS source
WORKDIR /go/src
ARG VERSION=main
RUN git clone --depth=1 --branch=${VERSION} https://git.torproject.org/pluggable-transports/obfs4.git .

FROM docker.io/library/golang:1.17-alpine AS build
COPY --from=source /go/src /go/src
WORKDIR /go/src/obfs4proxy
RUN if [[ "`go env | grep "^GOARCH=" | sed 's:GOARCH="\(.*\)":\1:'`" != "arm" ]]; then export PIE="-buildmode=pie"; fi
RUN CGO_ENABLED=0 go build -ldflags '-extldflags "-static" -w -s -buildid=' -trimpath $PIE .

FROM scratch
COPY --from=build /go/src/obfs4proxy/obfs4proxy /obfs4proxy
