name: Docker

on:
  schedule:
    - cron: '20 16 * * 5'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  ghcr_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log-in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base
        uses: docker/build-push-action@v3
        with:
          context: torbase/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/torbase:latest

      - name: Build and push proxy
        uses: docker/build-push-action@v3
        with:
          context: torproxy/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/torproxy:latest

      - name: Build and push obsf4-bin
        uses: docker/build-push-action@v3
        with:
          context: obfs4/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/obfs4:latest

      - name: Build and push obfs4-proxy
        uses: docker/build-push-action@v3
        with:
          context: obfs4-proxy/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/obfs4-proxy:latest

      - name: Build and push obfs4-bridge
        uses: docker/build-push-action@v3
        with:
          context: obfs4-bridge/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/obfs4-bridge:latest

      - name: Build and push snowflake-bin
        uses: docker/build-push-action@v3
        with:
          context: snowflake/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/snowflake:latest

      - name: Build and push snowflake-proxy
        uses: docker/build-push-action@v3
        with:
          context: snowflake-proxy/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/snowflake-proxy:latest

      - name: Build and push snowflake-standalone
        uses: docker/build-push-action@v3
        with:
          context: snowflake-standalone/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/snowflake-standalone:latest

      - name: Build and push onionshare
        uses: docker/build-push-action@v3
        with:
          context: onionshare/
          platforms: linux/amd64,linux/386,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/onionshare:latest
