name: Docker

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '12 21 * * *'

env:
  REGISTRY: ghcr.io

jobs:
  ghcr_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log-in to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base
        uses: docker/build-push-action@v2
        with:
          context: torbase/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/torbase:latest

      - name: Build and push proxy
        uses: docker/build-push-action@v2
        with:
          context: torproxy/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY }}/${{ github.actor }}/torproxy:latest

      - name: Build and push obsf4-bin
        uses: docker/build-push-action@v2
        with:
          context: obfs4/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/obfs4:latest

      - name: Build and push obfs4-proxy
        uses: docker/build-push-action@v2
        with:
          context: obfs4-proxy/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/obfs4-proxy:latest

      - name: Build and push obfs4-bridge
        uses: docker/build-push-action@v2
        with:
          context: obfs4-bridge/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/obfs4-bridge:latest
