name: Docker-onionshare

on:
  schedule:
    - cron: '20 16 * * 5'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  ghcr_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log-in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push onionshare
        uses: docker/build-push-action@v4
        with:
          context: onionshare/
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/onionshare:latest
