name: remove-old
on:
  workflow_dispatch:
  schedule:
    - cron: '10 16 * * 5'
jobs:
  remove-old:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old tailscale
        uses: smartsquaregmbh/delete-old-packages@v0.5.0
        with:
          token: ${{ secrets.PAT }}
          user: ${{ github.actor }}
          type: container
          keep: 12
          names: |
            torbase
            torproxy
            snowflake
            obfs4
            obfs4-bridge
            obfs4-proxy
            snowflake-proxy
            snowflake-standalone
            arti
            dohproxy
            i6r9c
            tailscale
