name: remove old snowflake-proxy
on:
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * 6'
jobs:
  remove-old-snowflake-proxy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/delete-package-versions@v4
       with:
          package-name: 'snowflake-proxy'
          package-type: 'container'
          min-versions-to-keep: 30
          delete-only-untagged-versions: 'true'
          token: ${{ secrets.PAT }}
