name: remove old obfs4
on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * 6'
jobs:
  remove-old-obfs4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'lyrebird'
          package-type: 'container'
          min-versions-to-keep: 30
          delete-only-untagged-versions: 'true'
          token: ${{ secrets.PAT }}
