name: remove orphan
on:
  workflow_dispatch:
jobs:
  remove-orphan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          owner: 'guest42069'
          package-name: 'arti'
          package-type: 'container'
          min-versions-to-keep: 0
          token: ${{ secrets.PAT }}
